# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170917_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='confidence_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='grade_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='grade_section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='problem_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='topics',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='conversation',
            name='violence_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
