# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_incident_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='request_kind',
            field=models.NullBooleanField(),
        ),
    ]
