# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_incident_request_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ended',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_requested',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='incident',
            name='proof_requested',
            field=models.NullBooleanField(),
        ),
    ]
