# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171210_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location_requested',
            field=models.NullBooleanField(),
        ),
    ]
