# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_conversation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sentiment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sentiment_value',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
