# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_policestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='name',
            field=models.CharField(default='Comisaria', max_length=100),
            preserve_default=False,
        ),
    ]
