# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_policestation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='indentity_required',
            field=models.NullBooleanField(),
        ),
    ]
