# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_incident_indentity_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
